---
name: Habu
author: bitrule
version: "2024.505"
api: 5.0.0
main: bitrule\practice\Habu
softdepend:
- Gorufus
permissions:
  arena.command:
    default: op
  arena.command.knockback:
    default: op
  arena.command.createkit:
    default: op
  arena.command.create:
    default: op
  arena.command.save:
    default: op
  arena.command.edit:
    default: op
  arena.command.yaw:
    default: op
  practice.command.joinqueue:
    default: true
  kb.command:
    default: op
  kb.command.create:
    default: op
  kb.command.horizontal:
    default: op
  kb.command.vertical:
    default: op
  kb.command.highestlimit:
    default: op
  kb.command.hitdelay:
    default: op
  practice.command.durability:
    default: op
...
