---
name: Habu
author: bitrule
version: "2024.505"
api: 5.0.0
main: bitrule\practice\Habu
loadbefore:
- Parties
permissions:
  arena.command:
    default: op
  arena.command.knockback:
    default: op
  arena.command.createkit:
    default: op
  arena.command.toggleparty:
    default: op
  arena.command.create:
    default: op
  arena.command.save:
    default: op
  arena.command.edit:
    default: op
  arena.command.yaw:
    default: op
  arena.command.corner:
    default: op
  practice.command.events:
    default: op
  practice.command.events.start:
    default: op
  practice.command.duel:
    default: true
  practice.command.accept:
    default: true
  practice.command.joinqueue:
    default: true
  practice.command.leavequeue:
    default: true
  kb.command:
    default: op
  kb.command.create:
    default: op
  kb.command.horizontal:
    default: op
  kb.command.vertical:
    default: op
  kb.command.highestlimit:
    default: op
  kb.command.hitdelay:
    default: op
  kb.command.info:
    default: op
  practice.command.durability:
    default: op
...
