---
name: BitrulePractice
author: bitrule
version: "2024.505"
api: 5.0.0
main: bitrule\practice\Practice
permissions:
  arena.command:
    default: op
  arena.command.createkit:
    default: op
  arena.command.create:
    default: op
  arena.command.save:
    default: op
  practice.command.joinqueue:
    default: true
...
