sumo-waiting-time: 30

duel:
  end-countdown: 5

ffa:
  build:
    world: 'BuildFFA'
    kit: 'BuildFFA'
  sumo:
    world: 'SumoFFA'
    kit: 'SumoFFA'
    anti_clean: true # Enable the anti-clean feature